### ISSUE TITLE
Feed and Tracery Geists

### ISSUE THREAD

**Issue by gordonbrander** [subconsciousnetwork/subconscious#16]
Umbrella issue for tracking launch of basic feed with hardcoded Tracery-based Geists.

## TODO

Architecture:

- [x] Refactor architecture to allow for multiple tabs https://github.com/subconsciousnetwork/subconscious/pull/334
- [ ] Persist generated Geist stories
- [ ] Load feed from persisted stories

Geists:
- [ ] Resurface random notes
- [x] Concept collider https://github.com/subconsciousnetwork/subconscious/pull/340
- [ ] On this day https://github.com/subconsciousnetwork/subconscious/issues/335
- [ ] Idea prompts https://github.com/subconsciousnetwork/subconscious/issues/353
- [x] Zettelkasten prompts

## Resources and docs

- Feed https://github.com/gordonbrander/subconscious/wiki/Subconscious-Feed
- Geists https://github.com/gordonbrander/subconscious/wiki/Subconscious-Geists
  - Prompts https://github.com/gordonbrander/subconscious/wiki/Prompt

**Comment by gordonbrander** [comment]
Closing. We now have Noosphere integration, and will prioritize integrating remote Geists first.
