### ISSUE TITLE
Block-based editor

### ISSUE THREAD

**Issue by gordonbrander** [subconsciousnetwork/subconscious#214]
Basic functionality:
- [x] #881 
- [x] #981 
- [ ] #1042
- [ ] #982
- [x] #983
- [x] #987
- [x] https://github.com/subconsciousnetwork/subconscious/pull/1010
- [x] #1041 
- [ ] #1009 
- [x] #1043

Possible feature enhancements:

- [ ] https://github.com/subconsciousnetwork/subconscious/issues/1039
- [ ] https://github.com/subconsciousnetwork/subconscious/issues/1038

**Comment by gordonbrander** [comment]
Looks like iOS16 has TextKit2 https://developer.apple.com/documentation/uikit/uitextview/4018418-textlayoutmanager

**Comment by bfollington** [comment]
Currently doing discovery on TextKit 2 integration in https://github.com/subconsciousnetwork/ObservableStoreDemo

Once we have found an approach that's viable I'll start integrating this into the main app.

**Comment by gordonbrander** [comment]
Approaching this with a stack of UITextViews in UIKit. See https://github.com/subconsciousnetwork/subconscious/pull/881
