### ISSUE TITLE
`main` should be an evergreen branch

### ISSUE THREAD

**Issue by gordonbrander** [subconsciousnetwork/subconscious#472]
## TODO

- [x] Flag for Noosphere #471 fixed by #473
- [x] Lock SHA for reproducible builds https://github.com/subconsciousnetwork/subconscious/pull/476
- [x] Add branch protection to enforce linear history
- [x] CI tests https://github.com/subconsciousnetwork/subconscious/pull/445

## Background motivation

Over the weekend, our TestFlight build expired. I was able to bump the build number and redeploy. However, the event exposed a number of issues with the way we manage `main` branch.

### Postmortem

- Database rebuild logic was broken in the last deployed tag [0.0.7](https://github.com/subconsciousnetwork/subconscious/releases/tag/0.0.7%2B1). We use this logic to migrate the database to new schemas.
- We fixed the database rebuild logic in https://github.com/subconsciousnetwork/subconscious/commit/5897c0cb4158201f33472ad4a890d2fca396e30a
    - Root cause was a bug related to `FileManager.default.removeItem(atPath:)`, and was fixed by using `FileManager.default.removeItem(at:)` instead. [See code for fix](https://github.com/subconsciousnetwork/subconscious/commit/5897c0cb4158201f33472ad4a890d2fca396e30a#diff-ab7ffc52a85ac83cd4ac02e124560b9d1000c363c30d6738e3cb520f0792a887R717).
- However https://github.com/subconsciousnetwork/subconscious/commit/5897c0cb4158201f33472ad4a890d2fca396e30a was also the PR where we introduced basic Noosphere features.
- We do not yet wish to roll out Noosphere to users, meaning we could not tag and roll out the PR with the database rebuild fix, or subsequent PRs.
- Redeploying 0.0.7 worked because there was no database rebuild to apply (same database version). However, this situation easily could have put us into a position where we needed to create a hotfix branch. Bad! 

In summary, our `main` branch violated the not-rocket-science rule. https://graydon2.dreamwidth.org/1597.html

> The Not Rocket Science Rule Of Software Engineering:
> automatically maintain a repository of code that always passes all the tests

### Other learnings

- TestFlight revokes the app when the build expires, but it DOES NOT delete the user's `Files/Subconscious` directory where local files are installed (good).
- Users are able to re-install the TestFlight without a new invite (it re-appears in your TestFlight app).
- Re-deploying same build goes through an expedited TestFlight review/deploy process. The build was available seconds after I bumped the build number.

### Solution going forward

- `main` should be maintained as an evergreen branch that can be tagged and deployed from at any time.
- `main` should have linear history
- Code should not land on `main` unless all tests pass.
- All features that we do not want to deploy to users should be hidden behind `Config` flags.
- Additionally, database rebuild fix should have been a separate stand-alone PR.

This will require more disciplined use of `Config` flags.
