### ISSUE TITLE
Subconscious Beta Multiplayer MVP User Stories

### ISSUE THREAD

**Issue by gordonbrander** [subconsciousnetwork/subconscious#482]
# Subconscious Beta MVP

Managing notes:

- [x] https://github.com/subconsciousnetwork/subconscious/issues/12
- [x] https://github.com/subconsciousnetwork/subconscious/issues/37
- [x] https://github.com/subconsciousnetwork/subconscious/issues/66

Finding/creating a note:

- [x] As a user, I want to create a new note, so I can jot down new thoughts.
- [x] https://github.com/subconsciousnetwork/subconscious/issues/406
- [x] https://github.com/subconsciousnetwork/subconscious/issues/72
    - [x] As a user, I want to search for a note, so I can quickly find the note I am looking for.
    - [x] As a user, when I am creating a new note, I want to see related notes on this topic, so that I can continue an old note instead of creating a duplicate new one.

Writing a note:

- [x] https://github.com/subconsciousnetwork/subconscious/issues/365
- [x] https://github.com/subconsciousnetwork/subconscious/issues/13
    - [x] As a user, when I am linking to a note, I want to see suggested notes from my sphere, so I can discover related notes to connect.
    - [x] As a user, when I am linking to a note, I want to see suggested notes from my sphere, so I can connect notes without having to memorize links.
- [x] https://github.com/subconsciousnetwork/subconscious/issues/551
- [x] #518

Browsing:

- [x] https://github.com/subconsciousnetwork/subconscious/issues/451
- [x] https://github.com/subconsciousnetwork/subconscious/issues/210
- [x] https://github.com/subconsciousnetwork/subconscious/issues/320
- [x] https://github.com/subconsciousnetwork/subconscious/issues/323

Note audience:

- [x] #519
- [x] https://github.com/subconsciousnetwork/subconscious/issues/368

User profiles/following:

- [x] https://github.com/subconsciousnetwork/subconscious/issues/321
- [x] https://github.com/subconsciousnetwork/subconscious/issues/418
- [x] #520
- [x] https://github.com/subconsciousnetwork/subconscious/issues/480
- [x] #523
- [x] #522
- [x] #478 

Discovery:

- [x] #536

My Profile:

- [x] #524
- [x] #526
- [x] #527

Syncing:

- [x] #531
- [x] #532

Recovery:

- [x] #529

Name system:

- [x] Name system publishing to IPFS
    - [x] As a user, I want my identity and content to be portable between services
    - [x] https://github.com/subconsciousnetwork/subconscious-ops/pull/71

First run:

- [x] https://github.com/subconsciousnetwork/subconscious/issues/20
- [x] https://github.com/subconsciousnetwork/subconscious/issues/513

Beta onboarding:

- [x] #534
- [x] #533
- [x] https://github.com/subconsciousnetwork/subconscious/issues/468

## Beta 2

See https://github.com/subconsciousnetwork/subconscious/issues/535
