### ISSUE TITLE
Subconscious Beta 2 User Stories

### ISSUE THREAD

**Issue by gordonbrander** [subconsciousnetwork/subconscious#535]
Followup from #482 

## Stories

Managing notes:

- [ ] As a user, I want to un-publish/revoke a published note, so I can correct mistakes or remove unwanted notes.

Finding/creating notes:

- [ ] As a user, I want to see recently and frequently edited notes, so I can develop my trains of thought.

Writing a note:

- [ ] As a user, I want to be able to split parts of a note into separate notes, so I can create atomic notes.

Note audience:

- [ ] As a user, I want to encrypt and sync my private notes, so I have access to them on all my devices.

Sharing:

- [ ] As a user, I want to access my public notes on the web, so I can share them outside of Subconscious.

User/profiles/following:

- [ ] As a user, when visiting a profile, I want to see most-frequently-linked-to notes for that sphere, so I can see the major themes they think about.
- [ ] As a user, when visiting a profile, I want to see backlinks count, so I can get a sense of whether their content is popular and worth linking to.
- [ ] As a user, I want to block people that bother me, so I am no longer bothered by them.
- [ ] As a user, I want to discover high-quality accounts to follow, so I can be inspired by their thoughts.

Feed:

- [ ] #528 

Geists:

- [ ] As a user, I want to discover and follow geists, so they can follow my notebook and provide generative provocations in my feed.
- [ ] As a user, I want to block Geists, so they can not follow my notebook.

Syncing:

- [ ] As a user, I want to sync my notes across multiple devices, so I can have access to them anywhere.
- [ ] https://github.com/subconsciousnetwork/subconscious/issues/495

Ownership:

- [ ] As a user, I want to sync/export all of my content to my desktop as text files, so I can credibly exit at any time.

Recovery:

- [ ] As a user, when I have lost my device, or lost access to my account, I want to authorize someone to back up my mnemonic, so I can recover my sphere, even if I've lost my mnemonic
