### ISSUE TITLE
Subconscious Beta MVP bugs

### ISSUE THREAD

**Issue by gordonbrander** [subconsciousnetwork/subconscious#730]
Followup to #482 

- [x] Bump 0.0.7 on TestFlight
- [x] https://github.com/subconsciousnetwork/subconscious/issues/729
- [ ] https://github.com/subconsciousnetwork/subconscious/issues/723
- [ ] https://github.com/subconsciousnetwork/subconscious/issues/682

**Comment by gordonbrander** [comment]
Closing in favor of tracking in team sprint goals.
